stages:
  - push

push:
  image: debian
  stage: push
  script:
    - apt-get update && apt-get install -y git
    - git checkout $CI_BUILD_REF_NAME
    - git remote add github https://$USER:$PASSWORD@github.com/SvenDub/mirror-test.git
    - git push -u github $CI_BUILD_REF_NAME

